"""
MAVLink Telemetry Interface -- SIMULATED
=======================================
Module: backend.mavlink_interface
Author: AeroTwin Engineering Team

SIMULATION DISCLAIMER:
    This module simulates the behavior of a real MAVLink/Pixhawk hardware
    interface. No physical hardware, serial port, or live MAVLink stream is
    involved. All "received" bytes are generated by replaying mission CSV
    data through a custom binary framing protocol that mirrors the MAVLink v2
    wire format.

    What this accurately models:
      - MAVLink v2 packet framing structure (header, seq, sysid, compid, msgid, payload, CRC)
      - A custom message ID 50001 carrying 14 AeroTwin telemetry channels
      - 1 Hz streaming cadence matching real sensor sample rates
      - Packet sequencing and CRC-16 (MCRF4XX polynomial) as used in MAVLink v2

    What requires real hardware to validate:
      - Actual Pixhawk 6C USB/serial connection
      - Real sensor noise and electromagnetic interference profiles
      - Hardware-in-the-loop (HIL) latency and jitter under flight conditions

Usage:
    iface = MAVLinkInterface(system_id=1, component_id=1)
    for packet_bytes in iface.simulate_pixhawk_stream("data/raw/test/mission_001.csv"):
        telemetry = iface.parse_telemetry(packet_bytes)
        print(telemetry)
"""

import struct
import time
import csv
import math
from pathlib import Path
from typing import Iterator, Optional

# ---------------------------------------------------------------------------
# MAVLink v2 framing constants (mirrors mavlink2 wire spec)
# ---------------------------------------------------------------------------
MAVLINK_STX_V2  = 0xFD
AEROTWIN_MSG_ID = 50001
PAYLOAD_FORMAT  = "<14f"        # 14 x float32 little-endian = 56 bytes
PAYLOAD_LEN     = struct.calcsize(PAYLOAD_FORMAT)  # 56
HEADER_LEN      = 10
CRC_EXTRA       = 0xA5

CHANNEL_NAMES = [
    "rpm", "true_cht", "sensor_cht", "egt",
    "oil_pressure", "oil_temp", "fuel_flow", "vibration",
    "battery_voltage", "injection_timing", "health_index",
    "altitude", "ambient_temp", "throttle"
]


def _crc16_mcrf4xx(data: bytes) -> int:
    """CRC-16 MCRF4XX -- polynomial used in MAVLink v2 checksums."""
    crc = 0xFFFF
    for byte in data:
        tmp = byte ^ (crc & 0xFF)
        tmp ^= (tmp << 4) & 0xFF
        crc = ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xFFFF
    return crc


class MAVLinkInterface:
    """
    [SIMULATED] MAVLink v2 interface mimicking a Pixhawk 6C autopilot.
    In a real deployment this would open a serial port via pyserial or a UDP
    socket and use the pymavlink library. Here all I/O is replaced by
    in-process byte generation from CSV data.
    """

    def __init__(self, system_id: int = 1, component_id: int = 200):
        self.system_id    = system_id
        self.component_id = component_id
        self._seq         = 0
        self.packets_sent = 0
        self.packets_parsed = 0

    def pack_telemetry(self, telemetry: dict) -> bytes:
        """Pack telemetry dict -> MAVLink v2 binary frame (68 bytes)."""
        channels = tuple(float(telemetry.get(ch, 0.0)) for ch in CHANNEL_NAMES)
        payload  = struct.pack(PAYLOAD_FORMAT, *channels)
        msgid_bytes = struct.pack("<I", AEROTWIN_MSG_ID)[:3]
        header = bytes([
            MAVLINK_STX_V2, PAYLOAD_LEN, 0x00, 0x00,
            self._seq & 0xFF, self.system_id, self.component_id,
        ]) + msgid_bytes
        crc_body = header[1:] + payload + bytes([CRC_EXTRA])
        crc = _crc16_mcrf4xx(crc_body)
        self._seq = (self._seq + 1) & 0xFF
        self.packets_sent += 1
        return header + payload + struct.pack("<H", crc)

    def parse_telemetry(self, packet_bytes: bytes) -> Optional[dict]:
        """Parse a MAVLink v2 frame back to telemetry dict. Returns None on CRC failure."""
        total_expected = HEADER_LEN + PAYLOAD_LEN + 2
        if len(packet_bytes) < total_expected or packet_bytes[0] != MAVLINK_STX_V2:
            return None
        crc_received = struct.unpack_from("<H", packet_bytes, HEADER_LEN + PAYLOAD_LEN)[0]
        crc_body = packet_bytes[1:HEADER_LEN + PAYLOAD_LEN] + bytes([CRC_EXTRA])
        if _crc16_mcrf4xx(crc_body) != crc_received:
            return None
        values = struct.unpack_from(PAYLOAD_FORMAT, packet_bytes, HEADER_LEN)
        self.packets_parsed += 1
        return dict(zip(CHANNEL_NAMES, values))

    def simulate_pixhawk_stream(
        self,
        mission_csv_path: str,
        playback_speed: float = 1.0,
        realtime: bool = False
    ) -> Iterator[bytes]:
        """
        [SIMULATED] Replay a mission CSV as MAVLink binary packets at 1 Hz cadence.
        Yields one packet per CSV row.
        """
        path = Path(mission_csv_path)
        if not path.exists():
            raise FileNotFoundError(f"[SIMULATED] Mission CSV not found: {mission_csv_path}")
        interval = 1.0 / max(0.1, playback_speed)
        with open(path, newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                telem = {}
                for ch in CHANNEL_NAMES:
                    try:
                        telem[ch] = float(row.get(ch, 0.0) or 0.0)
                    except (ValueError, TypeError):
                        telem[ch] = 0.0
                yield self.pack_telemetry(telem)
                if realtime:
                    time.sleep(interval)

    def link_stats(self) -> dict:
        return {
            "packets_sent":    self.packets_sent,
            "packets_parsed":  self.packets_parsed,
            "seq_counter":     self._seq,
            "simulation_note": "SIMULATED -- no physical hardware involved"
        }


if __name__ == "__main__":
    iface = MAVLinkInterface()
    test_telem = {
        "rpm": 5200.0, "true_cht": 165.3, "sensor_cht": 166.1, "egt": 610.5,
        "oil_pressure": 68.4, "oil_temp": 92.1, "fuel_flow": 5.6, "vibration": 0.12,
        "battery_voltage": 13.8, "injection_timing": 28.5, "health_index": 0.94,
        "altitude": 2800.0, "ambient_temp": 288.15, "throttle": 0.68
    }
    raw = iface.pack_telemetry(test_telem)
    print(f"[SIMULATED] Packed: {len(raw)} bytes")
    recovered = iface.parse_telemetry(raw)
    assert abs(recovered["rpm"] - test_telem["rpm"]) < 0.01
    print("[SIMULATED] Pack/parse round-trip: PASSED")
